config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :items
  resources :businesses

  get    '/signup',       to: 'users#new'

  get    '/login',        to: 'sessions#new'
  post   '/login',        to: 'sessions#create'
  delete '/logout',       to: 'sessions#destroy'

  root 'home#index'
end

app/models/business.rb
# frozen_string_literal: true

class Business < ActiveRecord::Base
  belongs_to :user

  has_many :items, inverse_of: :business

  validates :user, presence: true
end

app/models/item.rb
# frozen_string_literal: true

class Item < ActiveRecord::Base
  belongs_to :business

  validates :name, :price, :business, presence: true
  validates :name, length: { minimum: 3, maximum: 64 }
  validates :price, length: { minimum: 0, maximum: 1_000_000_000 }, numericality: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ActiveRecord::Base
  has_secure_password

  has_one :business, inverse_of: :user
  accepts_nested_attributes_for :business, allow_destroy: true

  validates :first_name, :last_name, :email, :business, presence: true
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  def initialize
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper

  # make this methods accessible in view
  helper_method :current_user, :current_business

  # authenticate user for all controllers and all actions
  # unless specified otherwise in each controller
  before_filter :authenticate_user

  # authenticate user function, redirect to login page if not logged in
  def authenticate_user
    redirect_to login_path, notice: "Please login first" if current_user.blank?
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update]


  def show

  end

  def new
    @business = Business.new
  end

  def edit

  end

  def create
    @business = Business.new(business_params)
    @business.user = current_user
    if @business.save
      redirect_to @business, notice: 'business was successfully created.'
    else
      render :new
    end
  end

  def update
    if @business.update(business_params)
      redirect_to @business, notice: 'business was successfully updated.'
    else
      render :edit
    end
  end

  def set_business
    @business = Business.find(params[:id])
  end

  def business_params
    params.require(:business).permit(:name, :address, :city)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    # List all of the Items that are owned by the logged in User's Business
    if current_business.present?
      @items = Item.where(business_id: current_business.id)
    else
      # Unauthorized
      redirect_to root_url
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # check if user logged in, if not redirect to login page
    if current_user.present?
      redirect_to items_path
    else
      redirect_to login_path
    end
  end

  def signup
    @user = User.new
    # TODO: [TAKI-002] Finish the implementation of User registration
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]


  def index
    # List all of the Items that are owned by the logged in User's Business
    if current_business.present?
      @items = current_business.items
    else
    # If business not yet created, redirect to create a new business
      redirect_to new_business_path, notice: "Please create a business."
    end
  end

  def show

  end

  def new 
    @item = Item.new
  end

  def edit

  end

  def create
    @item = Item.new(item_params)
    @item.business = current_business
    if @item.save
      redirect_to @item, notice: 'item was successfully created.'
    else
      render :new
    end
  end

  def update
    if @item.update(item_params)
      redirect_to @item, notice: 'item was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_url, notice: 'item was successfully destroyed.'
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :price)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # skip authentication for methods
  skip_before_filter :authenticate_user, :only => [:new, :create]

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_url
    else
      flash.now[:alert] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_filter :authenticate_user, only: %i[new create]
  before_action :set_user, only: %i[show edit update]
  include SessionsHelper

  def show; end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)
    @user.business = Business.new

    if @user.save
      log_in @user
      redirect_to @user, notice: 'user was successfully created.'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'user was successfully updated.'
    else
      render :edit
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    current_user.nil?
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns the current Business logged-in user (if any).
  def current_business
    if current_user.present?
      @current_business ||= current_user.business
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/businesses/_form_fields.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class:'form-control', 
            minlength: 3, maxlength: 64 %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :address %>
        <%= f.text_field :address, class:'form-control', 
            minlength: 3, maxlength: 128 %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :city %>
        <%= f.text_field :city, class:'form-control', 
            minlength: 3, maxlength: 64 %>
      </div>
    </div>
  </div>
</div>

app/views/businesses/edit.html.erb
<div class="container-fluid">
  <nav class="breadcrumb">
    <%= link_to "Show Business", business_path(@business), class:"breadcrumb-item" %> /
    <span class="breadcrumb-item active">Edit Business</span>
  </nav>
</div>
<div class="container-fluid mb-25">
  <div class="row">
    <div class="col-sm-12">
      <h1>Edit business</h1>
    </div>
  </div>
</div>
<%= render 'shared/validates_errors', obj: @business %>
<%= form_for @business do |f| %>
  <%= render 'form_fields', f:f %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-6 col-md-4 col-lg-3">
        <%= f.submit 'Save', class: 'btn btn-success' %>
      </div>
    </div>
  </div>
<% end %>

app/views/businesses/new.html.erb
<div class="container-fluid mb-25">
  <div class="row">
    <div class="col-sm-12">
      <h1>New business</h1>
    </div>
  </div>
</div>
<%= render 'shared/validates_errors', obj: @business %>
<%= form_for @business do |f| %>
  <%= render 'form_fields', f:f %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-6 col-md-4 col-lg-3">
        <%= f.submit 'Save', class: 'btn btn-success' %>
      </div>
    </div>
  </div>
<% end %>

app/views/businesses/show.html.erb
<div class="container-fluid mb-25">
  <div class="row">
    <div class="col-sm-12">
      <h1>Show Business</h1>
    </div>
  </div>
</div>
<fieldset disabled>
  <%= form_for @business do |f| %>
    <%= render 'form_fields', f:f %>
  <% end %>
</fieldset>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-6 col-md-4 col-lg-3">
      <%= link_to "Edit", edit_business_path(@business), class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/items/_form_fields.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-8 col-md-6">
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class:'form-control', 
            minlength: 3, maxlength: 64, required: true %>
      </div>
    </div>
    <div class="col-sm-4 col-md-6">
      <div class="form-group">
        <%= f.label :price %>
        <%= f.number_field :price, class:'form-control', step:"0.01", 
            min:0.1, max:1_000_000_000, required: true %>
      </div>
    </div>
  </div>
</div>

app/views/items/edit.html.erb
<div class="container-fluid">
  <nav class="breadcrumb">
    <%= link_to "List Itens", items_path(), class:"breadcrumb-item" %> /
    <span class="breadcrumb-item active">Edit Item</span>
  </nav>
</div>
<div class="container-fluid mb-25">
  <div class="row">
    <div class="col-sm-12">
      <h1>Edit Item</h1>
    </div>
  </div>
</div>
<%= render 'shared/validates_errors', obj: @item %>
<%= form_for @item do |f| %>
  <%= render 'form_fields', f:f %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-6 col-md-4 col-lg-3">
        <%= f.submit 'Save', class: 'btn btn-success' %>
      </div>
    </div>
  </div>
<% end %>

app/views/items/index.html.erb
<% provide(:title, "Items") %>
<div class="row">
  <div class="col-md-12 mb-15">
    <div style="display:flex; align-items: center; justify-content: space-between">
      <h1 style="margin:0">Listing items</h1>
      <%= link_to "Add", new_item_path, class:'btn btn-success', style:'float:right' %>
    </div>
  </div>
</div>
<table class="item-list table table-hover table-striped table-bordered">
  <tr>
    <th>Item name</th>
    <th>Price</th>
    <th></th>
  </tr>

  <% @items.each do |item| %>
    <tr>
      <td><%= item.name %></td>
      <td><%= item.price %></td>
      <td>
        <%= link_to "edit", edit_item_path(item), class:"btn btn-xs btn-primary" %>
        <%= link_to "delete", item_path(item), class:"btn btn-xs btn-danger",
         method: :delete, data: { confirm: 'Are you sure about that?'} %>
      </td>
    </tr>
  <% end %>
</table>

app/views/items/new.html.erb
<div class="container-fluid">
  <nav class="breadcrumb">
    <%= link_to "List Itens", items_path(), class:"breadcrumb-item" %> /
    <span class="breadcrumb-item active">New Item</span>
  </nav>
</div>
<div class="container-fluid mb-25">
  <div class="row">
    <div class="col-sm-12">
      <h1>New Item</h1>
    </div>
  </div>
</div>
<%= render 'shared/validates_errors', obj: @item %>
<%= form_for @item do |f| %>
  <%= render 'form_fields', f:f %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-6 col-md-4 col-lg-3">
        <%= f.submit 'Save', class: 'btn btn-success' %>
      </div>
    </div>
  </div>
<% end %>

app/views/items/show.html.erb
<div class="container-fluid">
  <nav class="breadcrumb">
    <%= link_to "List Itens", items_path(), class:"breadcrumb-item" %> /
    <span class="breadcrumb-item active">Show Item</span>
  </nav>
</div>
<div class="container-fluid mb-25">
  <div class="row">
    <div class="col-sm-12">
      <h1>Show Item</h1>
    </div>
  </div>
</div>
<fieldset disabled>
  <%= form_for @item do |f| %>
    <%= render 'form_fields', f:f %>
  <% end %>
</fieldset>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-6 col-md-4 col-lg-3">
      <%= link_to "Edit", edit_item_path(@item), class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <a href="/"><h2 class="header-main">Taki Rails Interview</h1></a>
  <nav>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <ul>
          <li><%= link_to "Home", root_path() %></li>
          <% begin %>
            <li><%= link_to "Business", business_path(current_business)%></li>
          <% rescue%>
          <% end %>
          <li><%= link_to "Profile", user_path(current_user) %></li>
          <li class="divider"></li>
          <li>
            <%= link_to "Log out", logout_path, method: "delete" %>
          </li>
        </ul>
      <% else %>
        <li><%= link_to "Log in", login_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taki Rails Interview</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

  <%= render 'layouts/header' %>

  <div class="container">
    <!-- flash message -->
    <% if notice.present? %>
      <p id="notice"><%= notice %></p>
    <% end %>

    <% if alert.present? %>
      <p id="alert"><%= alert %></p>
    <% end %>


    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>

  </body>
</html>

app/views/shared/_validates_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h2>

    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form_fields.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-6 col-md-5">
      <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class:'form-control', 
            minlength: 3, maxlength: 64, required: true %>
      </div>
    </div>
    <div class="col-sm-6 col-md-7">
      <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class:'form-control', 
            minlength: 3, maxlength: 64, required: true %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class:'form-control', 
            minlength: 3, maxlength: 64, required: true %>
      </div>
    </div>
    <div class="col-sm-6 col-md-3">
      <div class="form-group">
        <%= f.label :password %>
        <%= f.text_field :password, class:'form-control', 
            minlength: 6, maxlength: 64 %>
      </div>
    </div>
    <div class="col-sm-6 col-md-3">
      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.text_field :password_confirmation, class:'form-control', 
            minlength: 6, maxlength: 64 %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container-fluid">
  <nav class="breadcrumb">
    <%= link_to "Show User", user_path(@user), class:"breadcrumb-item" %> /
    <span class="breadcrumb-user active">Edit User</span>
  </nav>
</div>
<div class="container-fluid mb-25">
  <div class="row">
    <div class="col-sm-12">
      <h1>Edit User</h1>
    </div>
  </div>
</div>
<%= render 'shared/validates_errors', obj: @user %>
<%= form_for @user do |f| %>
  <%= render 'form_fields', f:f %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-6 col-md-4 col-lg-3">
        <%= f.submit 'Save', class: 'btn btn-success' %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1 class="text-center">Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3" id="signup-form">
    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "invalid value") %>.</h2>

          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid mb-25">
  <div class="row">
    <div class="col-sm-12">
      <h1>Show User</h1>
    </div>
  </div>
</div>
<fieldset disabled>
  <%= form_for @user do |f| %>
    <%= render 'form_fields', f:f %>
  <% end %>
</fieldset>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-6 col-md-4 col-lg-3">
      <%= link_to "Edit", edit_user_path(@user), class: 'btn btn-primary' %>
    </div>
  </div>
</div>